Repository FTrost/5Psi, pull requests merged in 2021-03, with the labels that each got.

#9 Merge changes in statistical analysis
  src/expec_plot.pdf
  src/notebook_unit1.ipynb
Labels: enhancement

#10 Add rest of statistical analysis
  README.md
  environment.yml
  results/L2_Norm.pdf
  results/L2_Norm.txt
  results/correlations.txt
  src/notebook_unit1.ipynb
Labels: enhancement

#18 add documentation in new branch
  doc/Makefile
  doc/make.bat
  doc/source/conf.py
  doc/source/flow_chart
  doc/source/index.rst
  doc/source/modules.rst
  doc/source/psi5.rst
  src/psi5/__init__.py
  src/psi5/helper_functions.py
Labels: documentation

#20 add filter_data to helper_functions
  src/psi5/helper_functions.py
  src/psi5/stat_methods.py
Labels: enhancement

#26 Add test function for pairwise_corr
  src/psi5/stat_methods.py
  src/psi5/test/test_stat_methods.py
Labels: tests
